# Generated by Django 4.2.11 on 2024-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_organisation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
