# Generated by Django 4.2.11 on 2024-09-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_job_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='count',
            new_name='applicant_count',
        ),
    ]
