# Generated by Django 4.2.11 on 2024-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='org_access_code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
