# Generated by Django 4.2.11 on 2024-09-10 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0006_staff_org_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee',
            field=models.ManyToManyField(limit_choices_to={'role': 'USER'}, null=True, related_name='organization_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
