# Generated by Django 4.2.11 on 2024-09-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_alter_staff_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
