# Generated by Django 4.2.11 on 2024-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['name'], name='organisatio_name_51ea90_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['location'], name='organisatio_locatio_d34bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['longitude', 'latitude'], name='organisatio_longitu_6f9d56_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['admin'], name='organisatio_admin_i_f13676_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['staff_access_code'], name='organisatio_staff_a_72e8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['created_at'], name='organisatio_created_9f621a_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['updated_at'], name='organisatio_updated_66d0eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(fields=('staff_access_code',), name='unique_staff_code'),
        ),
    ]
