# Generated by Django 4.2.11 on 2024-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_organisation_organisatio_name_51ea90_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by'], name='organisatio_created_905e92_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organisation'], name='organisatio_organis_0cf68b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='organisatio_title_21714f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['start_date'], name='organisatio_start_d_5bb980_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['end_date'], name='organisatio_end_dat_a78ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['applicant_count'], name='organisatio_applica_e04bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by', 'organisation'], name='organisatio_created_201777_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['start_date', 'end_date'], name='organisatio_start_d_bf1c83_idx'),
        ),
    ]
