# Generated by Django 4.2.11 on 2024-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_job_organisatio_created_905e92_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='organisatio_job_id_2e6e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='organisatio_status_91dd18_idx'),
        ),
    ]
