# Generated by Django 4.2.11 on 2024-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_application_organisatio_job_id_2e6e2a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['organisation'], name='organisatio_organis_018045_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['org_access_code'], name='organisatio_org_acc_e57c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['organisation', 'org_access_code'], name='organisatio_organis_27284c_idx'),
        ),
    ]
