# Generated by Django 4.2.11 on 2024-09-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
