# Generated by Django 4.2.11 on 2024-09-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ORG_ADMIN', 'Organisation Admin'), ('ORG_STAFF', 'Organisation Staff'), ('ORG_HR', 'HR Representative')], default='USER', max_length=20),
        ),
    ]
